Messages:
  #use this everywhere with %prefix%
  prefix: "&8[ &eCute&6Bees &8]"
  help-usage: "%prefix% &cNot enough argument. &f/cb help"
  reload: "%prefix% &aPlugin has been reloaded!"
  wrong-configuration: "%prefix% &cError in your configuration!\n%prefix% &cPlease check your console and contact me on github if you cant fix it!"
  enable-world-usage: "%prefix% &c/cb enable <world>"
  enable-world: "%prefix% &aWorld successfully added to list"
  world-already-exists: "%prefix% &cThis world is already exists!"
  disable-world-usage: "%prefix% &c/cb disable <world>"
  disable-world: "%prefix% &aWorld successfully disabled!"
  world-not-exists: "%prefix% This world not exists in the list!"
  unknown-subcommand: "%prefix% &cWrong subcommand. Use &f/cb help"
  no-permission: "&cYou don't have enough permission for this action"
  customitems:
    open-inventory: "%prefix% &aCustomItems inventory opened!"
    create-item: "%prefix% &aCustomItem successfully created!"
    item-exists: "%prefix% &cThis item-key already exists!"
    create-usage: "%prefix% &a/cb create &ccustomitem <item-key> <material> <amount> <display-name> <chance>"
    item-key-usage:
      - "%prefix% &a/cb create customitem &c<item-key> <material> <amount> <display-name> <chance>"
      - "%prefix% &cAdd an item key, whatever you want(don't use spaces!!!)"
    material-usage:
      - "%prefix% &a/cb create customitem <item-key> &c<material> &c<amount> <display-name> <chance>"
      - "%prefix% &cAdd a valid material, like STONE"
    amount-usage:
      - "%prefix% &a/cb create customitem <item-key> <material> &c<amount> <display-name> <chance>"
      - "%prefix% &cAdd a valid amount from 1 to 64"
    display-name-usage:
      - "%prefix% &a/cb create customitem <item-key> <material> <amount> &c<display-name> <chance>"
      - "%prefix% &cAdd a valid displayname(don't use spaces in here, just in config)"
    chance-usage:
      - "%prefix% &a/cb create customitem <item-key> <material> <amount> <display-name> &c<chance>"
      - "%prefix% &cAdd a chance from 0 to 100"

CuteBees:
  #%bees-name%
  bee-name: "&eC&6u&et&6e&eB&6e&ee &8- &7%bee-health%&8/&7%bee-max-health%"
  bee-glowing: false
  custom-name-visible: true
  every-bee-baby: true